databases:
  - name: yamenthon
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: yamenthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m yamenthon
    region: frankfurt
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: ENV
        value: ANYTHING
      - key: SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DATABASE_URL
        fromDatabase:
          name: yamenthon
          property: connectionString   
    autoDeploy: false
